/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeon_crawl.Panels;

import dungeon_crawl.Controllers.DungeonCrawl;

/**
 *
 * @author Kieran
 */
public class BattlePanel extends javax.swing.JPanel {

    private DungeonCrawl dungeonCrawl;
    
    public BattlePanel(DungeonCrawl dungeonCrawl) {
        initComponents();
        this.dungeonCrawl = dungeonCrawl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameTitleLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        qButton = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        enemyPanel = new javax.swing.JPanel();
        enemyNameLabel = new javax.swing.JLabel();
        enemyHealthLabel = new javax.swing.JLabel();
        playerPanel = new javax.swing.JPanel();
        playerLabel = new javax.swing.JLabel();
        playerHealthLabel = new javax.swing.JLabel();
        battleActionPanel = new javax.swing.JPanel();
        battleActionLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gameTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameTitleLabel.setText("DUNGEON CRAWL");
        add(gameTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 60));

        sidePanel.setBackground(new java.awt.Color(200, 200, 200));
        sidePanel.setPreferredSize(new java.awt.Dimension(150, 400));

        qButton.setText("<html>\n<b>[ITEM NAME]</b>\n<br>\n# DMG\n<br>\n+# HEALTH\n<br>\n# TURN STUN\n</html>\n\n");
        qButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qButtonActionPerformed(evt);
            }
        });

        wButton.setText("<html>\n<b>[ITEM NAME]</b>\n<br>\n# DMG\n<br>\n+# HEALTH\n<br>\n# TURN STUN\n</html>\n\n");
        wButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wButtonActionPerformed(evt);
            }
        });

        eButton.setText("<html>\n<b>[ITEM NAME]</b>\n<br>\n# DMG\n<br>\n+# HEALTH\n<br>\n# TURN STUN\n</html>\n\n");
        eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });

        rButton.setText("<html>\n<b>[ITEM NAME]</b>\n<br>\n# DMG\n<br>\n+# HEALTH\n<br>\n# TURN STUN\n</html>\n\n");
        rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonActionPerformed(evt);
            }
        });

        quitButton.setText("QUIT");
        quitButton.setPreferredSize(new java.awt.Dimension(120, 40));
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(qButton)
                    .addComponent(rButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eButton))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(qButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        enemyPanel.setBackground(new java.awt.Color(220, 220, 220));

        enemyNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enemyNameLabel.setText("[ENEMY NAME]");

        enemyHealthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enemyHealthLabel.setText("HEALTH: ##");

        javax.swing.GroupLayout enemyPanelLayout = new javax.swing.GroupLayout(enemyPanel);
        enemyPanel.setLayout(enemyPanelLayout);
        enemyPanelLayout.setHorizontalGroup(
            enemyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enemyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enemyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enemyNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enemyHealthLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        enemyPanelLayout.setVerticalGroup(
            enemyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enemyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enemyNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(enemyHealthLabel)
                .addContainerGap())
        );

        add(enemyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 450, 80));

        playerPanel.setBackground(new java.awt.Color(220, 220, 220));

        playerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playerLabel.setText("PLAYER");

        playerHealthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playerHealthLabel.setText("HEALTH: ##");

        javax.swing.GroupLayout playerPanelLayout = new javax.swing.GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerHealthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        playerPanelLayout.setVerticalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(playerHealthLabel)
                .addContainerGap())
        );

        add(playerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 450, 80));

        battleActionPanel.setBackground(new java.awt.Color(220, 220, 220));

        battleActionLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        battleActionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        battleActionLabel.setText("YOU USED HIT!");

        javax.swing.GroupLayout battleActionPanelLayout = new javax.swing.GroupLayout(battleActionPanel);
        battleActionPanel.setLayout(battleActionPanelLayout);
        battleActionPanelLayout.setHorizontalGroup(
            battleActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(battleActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(battleActionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        battleActionPanelLayout.setVerticalGroup(
            battleActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(battleActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(battleActionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(battleActionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 450, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        //Game is saved before fight
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void qButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qButtonActionPerformed
        this.dungeonCrawl.userItem("Q");
    }//GEN-LAST:event_qButtonActionPerformed

    private void rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonActionPerformed
        this.dungeonCrawl.userItem("R");
    }//GEN-LAST:event_rButtonActionPerformed

    private void wButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wButtonActionPerformed
        this.dungeonCrawl.userItem("W");
    }//GEN-LAST:event_wButtonActionPerformed

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
        this.dungeonCrawl.userItem("E");
    }//GEN-LAST:event_eButtonActionPerformed
    
    public void updateEnemy(String name, String health) {
        this.enemyNameLabel.setText(name);
        this.enemyHealthLabel.setText(health);
    }
    
    public void updatePlayer(String health) {
        this.playerHealthLabel.setText(health);
    }
    
    public void updateBattleActionLabel(String text) {
        this.battleActionLabel.setText(text);
    }
    
    public void updateItemButtions(String[] items) {
        this.qButton.setText(items[0]);
        this.wButton.setText(items[1]);
        this.eButton.setText(items[2]);
        this.rButton.setText(items[3]);
    }
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel battleActionLabel;
    private javax.swing.JPanel battleActionPanel;
    private javax.swing.JButton eButton;
    private javax.swing.JLabel enemyHealthLabel;
    private javax.swing.JLabel enemyNameLabel;
    private javax.swing.JPanel enemyPanel;
    private javax.swing.JLabel gameTitleLabel;
    private javax.swing.JLabel playerHealthLabel;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JButton qButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton rButton;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton wButton;
    // End of variables declaration//GEN-END:variables
}
