/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeon_crawl.Panels;

/**
 *
 * @author Kieran
 */
public class GamePanel extends javax.swing.JPanel {

    private javax.swing.JLabel[][] labels = new javax.swing.JLabel[7][11];
    
    public GamePanel() {
        initComponents();
        //Create grid
        for (int i = 0; i < labels.length; i++) {
            for (int j = 0; j < labels[0].length; j++) {
                javax.swing.JLabel label = new javax.swing.JLabel();
                label.setText(i + ", " + j);
                label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                gridPanel.add(label);
                labels[i][j] = label;
            }
        }
    }
    
    public void updateGrid(String[][] string) {
        for (int i = 0; i < labels.length; i++) {
            for (int j = 0; j < labels[0].length; j++) {
                if (string[i][j] == null) {
                    labels[i][j].setText("");
                } else {
                    labels[i][j].setText(string[i][j]);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameTitleLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        gameIconInfoLabel = new javax.swing.JLabel();
        movementPanel = new javax.swing.JPanel();
        moveUpButton = new javax.swing.JButton();
        moveLeftButton = new javax.swing.JButton();
        moveRightButton = new javax.swing.JButton();
        moveDownButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        levelLabel = new javax.swing.JLabel();
        gridPanel = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gameTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameTitleLabel.setText("DUNGEON CRAWL");
        add(gameTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 60));

        sidePanel.setBackground(new java.awt.Color(200, 200, 200));
        sidePanel.setPreferredSize(new java.awt.Dimension(150, 400));

        gameIconInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gameIconInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameIconInfoLabel.setText("<html>\nE - ENEMY\n<br>\nI - ITEM\n<br>\nD - DOOR\n<br>\nX - PLAYER\n</html>");

        moveUpButton.setText("/\\");
            moveUpButton.setMaximumSize(new java.awt.Dimension(40, 40));
            moveUpButton.setMinimumSize(new java.awt.Dimension(40, 40));
            moveUpButton.setPreferredSize(new java.awt.Dimension(40, 40));
            moveUpButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    moveUpButtonActionPerformed(evt);
                }
            });

            moveLeftButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            moveLeftButton.setText("<");
            moveLeftButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
            moveLeftButton.setMaximumSize(new java.awt.Dimension(40, 40));
            moveLeftButton.setMinimumSize(new java.awt.Dimension(40, 40));
            moveLeftButton.setPreferredSize(new java.awt.Dimension(40, 40));
            moveLeftButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    moveLeftButtonActionPerformed(evt);
                }
            });

            moveRightButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            moveRightButton.setText(">");
            moveRightButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
            moveRightButton.setMaximumSize(new java.awt.Dimension(40, 40));
            moveRightButton.setMinimumSize(new java.awt.Dimension(40, 40));
            moveRightButton.setPreferredSize(new java.awt.Dimension(40, 40));
            moveRightButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    moveRightButtonActionPerformed(evt);
                }
            });

            moveDownButton.setText("\\/");
            moveDownButton.setMaximumSize(new java.awt.Dimension(40, 40));
            moveDownButton.setMinimumSize(new java.awt.Dimension(40, 40));
            moveDownButton.setPreferredSize(new java.awt.Dimension(40, 40));
            moveDownButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    moveDownButtonActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout movementPanelLayout = new javax.swing.GroupLayout(movementPanel);
            movementPanel.setLayout(movementPanelLayout);
            movementPanelLayout.setHorizontalGroup(
                movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movementPanelLayout.createSequentialGroup()
                    .addComponent(moveLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moveRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(movementPanelLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(moveDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(moveUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            movementPanelLayout.setVerticalGroup(
                movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movementPanelLayout.createSequentialGroup()
                    .addComponent(moveUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)
                    .addGroup(movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(moveLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(moveRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                    .addComponent(moveDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            quitButton.setText("QUIT");
            quitButton.setPreferredSize(new java.awt.Dimension(120, 40));
            quitButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    quitButtonActionPerformed(evt);
                }
            });

            levelLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            levelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            levelLabel.setText("LEVEL 1");

            javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
            sidePanel.setLayout(sidePanelLayout);
            sidePanelLayout.setHorizontalGroup(
                sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(levelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gameIconInfoLabel)
                        .addComponent(movementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addContainerGap())
            );
            sidePanelLayout.setVerticalGroup(
                sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(levelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(gameIconInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(movementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

            gridPanel.setLayout(new java.awt.GridLayout(7, 11));
            add(gridPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 430, 300));
        }// </editor-fold>//GEN-END:initComponents

    private void moveDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveDownButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitButtonActionPerformed

    private void moveUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveUpButtonActionPerformed

    private void moveLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLeftButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveLeftButtonActionPerformed

    private void moveRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveRightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveRightButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameIconInfoLabel;
    private javax.swing.JLabel gameTitleLabel;
    private javax.swing.JPanel gridPanel;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JButton moveDownButton;
    private javax.swing.JButton moveLeftButton;
    private javax.swing.JButton moveRightButton;
    private javax.swing.JButton moveUpButton;
    private javax.swing.JPanel movementPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
